name: integration-tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          start: npm run serve
          working-directory: cypress
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: b4ed260d-b619-4763-8bbf-1de51c80c46f
